Добавлены эндпоинты /films и /users
cpu-fan/java-filmorate pull request #1
Opened 2022-11-21 17:04 UTC by cpu-fan

Николай, привет! Оставил в коде небольшой вопрос в тестовом классе FilmControllerTest (188 стр.) по поводу реализации клиента и его использовании для двух тестовых контроллеров. Наверно в будущем будет правильнее уже не в коде их оставлять, а тут в PR. 🙂

2022-11-23 10:50 UTC, NikolaiDem requested changes

2022-11-23 10:50 UTC, NikolaiDem commented on pom.xml
> +		<dependency>
Лишняя зависимость.

2022-11-23 10:50 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        int id = films.size() + 1;
Такая генерация id может нарушить уникальность идентификатора фильма. Например, было 2 фильма с id  1 и 2. Первый фильм удалили, добавили новый, и ему указали id = 2.

2022-11-23 10:50 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        int id = users.size() + 1;
Такая генерация id может нарушить уникальность идентификатора юзера. Например, было 2 юзера с id 1 и 2. Первого юзера удалили, добавили новый, и ему указали id = 2.

2022-11-23 10:50 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2022-11-23 10:50 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @DaTa можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2022-11-23 10:50 UTC, NikolaiDem commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=trace
Не используется

2022-11-23 10:50 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film;
В каждом тесте user инициализируется заново, поэтому можно не выносить его в поле класса, а сделать локальной переменной.
Аналогично для UserControllerTest.

2022-11-23 20:08 UTC, cpu-fan commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=trace
Не совсем понял комментарий) Имеешь ввиду не используется потому что так не делают или в моем коде уровень логирования TRACE не используется?

2022-11-23 20:26 UTC, cpu-fan commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film;
Если вынести эти переменные film и user из полей тестовых классов, то тогда ведь в каждом тесте нужно будет создавать новые? Получится дублирование?

<img width="467" alt="Снимок экрана 2022-11-23 в 23 16 23" src="https://user-images.githubusercontent.com/64523108/203638652-3aac8efb-be1d-41d2-b361-065fb310cf62.png">

А если оставить в поле класса, то тогда они каждый раз инициализируются в setUp() и не нужно в каждом тесте их инициализировать по новой. А далее в остальных тестах просто изменяю как нужно.
Или я что-то упускаю? 🤔

2022-11-23 20:53 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Ок, спасибо, поправил) В теории об этом не говорилось, хотя были примеры использования @Data и @Builder одновременно 🤷‍♂️

2022-11-24 11:10 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film;
Ага, заметил, у тебя меняется лишь поле у объекта, а не происходит инициализация заново. Тогда пусть так

2022-11-24 11:15 UTC, NikolaiDem commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook=trace
А zalando  у тебя вообще используется? Если нет, то и проперти лишние)

2022-11-24 23:58 UTC, NikolaiDem approved these changes

2022-11-25 08:55 UTC, merged