Новая функциональность добавления друзей и лайков к фильмам
cpu-fan/java-filmorate pull request #2
Opened 2022-12-08 14:59 UTC by cpu-fan

Привет! 🙂 

<img src="https://user-images.githubusercontent.com/64523108/206476610-d2c90dba-4982-4837-9b34-26684f8e17de.png" width="250"/>

2022-12-09 13:58 UTC, NikolaiDem requested changes

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        e.getBindingResult().getAllErrors().forEach((error) -> {
Можно сделать через stream, сначала смапить все ошибки в defaultMessage, а потом все собрать в List.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setLikes() {
private

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setFriends() {
private

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilms().values();
Лучше из хранилища вернуть сразу List или Collection, ведь хранилище может быть не только inMemory с мапой. Потому для независимости от реализации хранилища лучше не завязываться на мапу.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilms().containsKey(id)) {
Лучше вызвать метод filmStorage.getFilmById(...) для проверки существования фильма.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        // Здесь и в методе deleteLike() изначально я сделал такую проверку, что если приходит недопустимый id, то
Сначала лучше вызвать getFilmById(...) и getUserById(...), чтобы проверить существование фильма и юзера, если кто-то из них не найден, то будет брошено соответствующее исключение с последующим 404 кодом ответа.
Аналогично для метода удаления лайка.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUsers().values();
Лучше из хранилища вернуть сразу List или Collection, ведь хранилище может быть не только inMemory с мапой. Потому для независимости от реализации хранилища лучше не завязываться на мапу.
Лучше из хранилища вернуть сразу List или Collection, ведь хранилище может быть не только inMemory с мапой. Потому для независимости от реализации хранилища лучше не завязываться на мапу.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUsers().containsKey(id)) {
Лучше вызвать метод userStorage.getUserById(...) для проверки существования юзера.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userId == friendId) {
В методах добавления и удаления друзей лучше сначала проверить, что пользователи существуют. Вызвать методы userStorage.getUserById(...)

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        film.getLikes().add(userId);
Лучше в Film добавить методы addLike(...) и removeLike(...) для соблюдения принципов Single Responsibility.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return Stream.of(user.getFriends().toArray())
Зачем из коллекции делать массив, можно сразу вызвать stream () у коллекции.

2022-12-09 13:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +                .filter(id -> Arrays.asList(otherUser.getFriends().toArray()).contains(id))
Здесь тоже массив лишний. И otherUser.getFriends() лучше вынести в отдельную переменную.

2022-12-09 19:52 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        film.getLikes().add(userId);
Впервые слышу о таком принципе, нужно будет почитать об этом, спасибо) Так же добавил аналогичные методы в User.

2022-12-09 20:33 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        // Здесь и в методе deleteLike() изначально я сделал такую проверку, что если приходит недопустимый id, то
getUserById() уже тут имеется, а getFilmById() вызывается непосредственно внутри filmStorage.addLike(filmId, userId). Если лучше сюда вынести в FilmService, вынесу, только скажи)

2022-12-09 20:49 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return Stream.of(user.getFriends().toArray())
Вот тут я довольно долго мучился и не смог ничего лучше придумать 😩 гугол не помог, либо я плохо искал из-за того что устал 😁
В общем, у множества Set нету ведь метода для извлечения содержащихся в нем элементов (например, как у мапы get()). А если не делать массив из этого Set, то дальше в стриме в промежуточную операцию .map(users::get) передается не стрим чисел, а стрим Stream<Set<Integer>> и из него мне никак не получается вытащить числа для .map(users::get). Пытался как-то применить перед этим .mapToInt(), но ни к чему так и не пришел(( 
Наведи меня в правильную сторону пожалуйста, ну или подскажи 😉

2022-12-09 20:50 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +                .filter(id -> Arrays.asList(otherUser.getFriends().toArray()).contains(id))
В отдельную переменную вынес, а вот с массивом та же история, что и в предыдущем комментарии.

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
>  import org.springframework.http.HttpStatus;
Неиспользуемые импорты.

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      public int getId() {
Вместо написания геттеров и сеттеров лучше использовать аннотации lombok-а @Getter, @Setter

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      public int getId() {
Вместо написания геттеров и сеттеров лучше использовать аннотации lombok-а @Getter, @Setter

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(id) != null) {
Достаточно только вызвать filmStorage.getFilmById(id);
null сейчас не вернется, метод бросит исключение.

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(id) != null) {
Достаточно только вызвать userStorage.getUserById(id);
null сейчас не вернется, метод бросит исключение.

2022-12-11 00:56 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return Stream.of(user.getFriends().toArray())
Например, так
        return user.getFriends().stream()
                .map(users::get)
                .collect(Collectors.toList());

2022-12-11 00:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +                .filter(id -> Arrays.asList(otherUser.getFriends().toArray()).contains(id))
Например, так
return user.getFriends().stream()
                .filter(otherUserFriends::contains)
                .map(users::get)
                .collect(Collectors.toList());

2022-12-11 01:00 UTC, NikolaiDem requested changes
Азат, остались финальные правки)

2022-12-11 18:50 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return Stream.of(user.getFriends().toArray())
Все оказалось так просто 😁 
На самом деле я примерно так тоже пробовал, только через Stream.of(), вот так:
```java
return Stream.of(user.getFriends())
                .map(users::get)
                .collect(Collectors.toList());
```
Результат совсем другой и вот в таком варианте и получался стрим из `Stream<Set<Integer>>` из которого мне и не удавалось вытащить числа.
А через твой вариант сразу все ок стало)) чего я о таком способе забыл, не понятно...

2022-12-12 14:01 UTC, NikolaiDem approved these changes

2022-12-12 14:39 UTC, merged