Сохранение состояния данных в БД
cpu-fan/java-filmorate pull request #3
Opened 2023-01-14 16:05 UTC by cpu-fan

Николай, привет! 

Наконец-то я приблизился к завершению 11 спринта) Ух, как же мало времени было на занятия в этот раз. Поэтому надеюсь, что проверка моего кода не вызовет много дискомфорта и крови из глаз))

2023-01-15 21:23 UTC, NikolaiDem requested changes

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +import java.util.Arrays;
Лишняя зависимость.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        e.printStackTrace();
Лучше использовать запись через логгер чем напрямую в консоль. У логгера больше гибкости к настройке логирования. 
log.error(…)

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Map<String, Object> toMap() {
Отлично

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Builder
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/MpaRating.java
> +@Builder
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    private final GenreDaoImpl genreDaoImpl;
Лучше использовать интерфейс, чтобы не зависеть от реализации.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaRatingService.java
> +    private final MpaRatingDaoImpl mpaRatingDao;
Лучше использовать интерфейс, чтобы не зависеть от реализации.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final UserService userService;
Добавить логирование во все методы.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Добавить логирование во все методы.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaRatingService.java
> +public class MpaRatingService {
Добавить логирование во все методы.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
Добавить логирование во все методы.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "select * from films";
Здесь сразу можно добавить джойн к mpa_ratings, чтобы избавиться от дополнительного запроса.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDaoImpl.java
> +        for (Genre filmGenre : filmGenres) {
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "select * from FILMS where id in (select FILM_ID from FILM_LIKES group by FILM_ID " +
Лучше использовать джойн к FILM_LIKES вместо вложенного запроса.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        int filmId = rs.getInt("id");
Когда этот метод вызывается для списка фильмов, то здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по 3 запроса (на получение mpa, жанров и лайков), то есть дополнительных N (*3) запросов.
Лучше mpa получить в том же запросе, где получаются фильмы (добавить джойн к mpa).
А жанры можно получить одним запросом, но для всех фильмов сразу. (То есть сначала сконструировать все фильмы, а потом для всего списка фильмов вызвать метод для получения жанров). Тогда останется только распределить их по фильмам. Аналогично для лайков.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        MpaRating mpaRating = mpaRatingDao.getMpaRatingById(film.getMpa().getId());
mpa можно получить путем джойна films к mpa_ratings.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        userDbStorage.getUserById(userId);
Существование юзера проверятся же в сервисе.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        getFilmById(filmId);
Существование фильма тоже можно проверить в сервисе.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +     Film updateFilm(Film film);
Code style : лишний пробел.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        getUserById(userId);
Существование юзеров лучше проверить сразу в сервисе.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public User addFriend(int userId, int friendId) {
А если юзер сам себя добавляет в друзья?

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                log.error(String.format("Пользователь id = %d уже отправлял заявку пользователю id = %d",
Сообщение об ошибке дважды дублируется, лучше вынести в переменную:
String messageError;
            if (!isConfirmed.get(0)) {
                messageError = String.format("Пользователь id = %d уже отправлял заявку пользователю id = %d", userId, friendId);
            } else {
                messageError = String.format("Пользователь id = %d уже принял заявку пользователя id = %d", friendId, userId);
            }
            log.error(messageError);
            throw new ValidationException(messageError);

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            String sqlForUpdate = "update friends set user_id = ?, friend_id = ?, is_confirmed = ? " +
А зачем обновлять "user_id = ?, friend_id = ?" ?

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        if (isHaveFriendRequest.size() > 0 && !isHaveFriendRequest.get(0)) {
А если истинно условие isHaveFriendRequest.size() > 0 && isHaveFriendRequest.get(0) ?

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql = "select * from users where id in (select friend_id from friends where user_id = ?)";
Вместо вложенного запроса лучше использовать джойн.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql = "select * from users where id in (select friend_id from friends where user_id = ?)";
Пусть таблица друзей такова:
1,3,true
2,3,true
4,3,true
и мы хотим найти друзей юзера с id=3.
Получим, что у него нет друзей?)

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        List<User> userFriends = getFriends(userId);
Лучше использовать джойн юзеров к друзьям, чтобы найти общих друзей одним запросом.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    private User mapRowUser(ResultSet rs, int rowNum) throws SQLException {
Здесь тоже проблема N + 1. Друзей юзера лучше получить одним запросом для всего списка сразу.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/resources/data.sql
> +insert into MPA_RATINGS (NAME)
Лучше использовать merge into, чтобы не было ошибок при следующем деплое на сервер и запуске скрипта бд.
Аналогично для жанров.

2023-01-15 21:23 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            return jdbcTemplate.queryForObject(sql, this::mapRowFilm, id);
Лучше использовать jdbcTemplate.query(...), который вернет список фильмов. Если список пуст, то бросить NotFoundException. Так можно избавиться от лишней обработки EmptyResultDataAccessException.
Аналогично для остальных классов репозиториев.

2023-01-17 22:41 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        int filmId = rs.getInt("id");
Вот здесь так и не понял как это можно сделать. Нужен видимо какой-то эквивалент jdbcTemplate.batchUpdate только который будет еще и возвращать список как, например, jdbcTemplate.query? 
Как сделал, в итоге, это вероятно совсем не правильно, а просто переделал предыдущий вариант другим способом 😕

2023-01-17 22:41 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    private User mapRowUser(ResultSet rs, int rowNum) throws SQLException {
Тут как и в mapRowFilms не совсем понял.

2023-01-17 22:59 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        String sql = "select * from users where id in (select friend_id from friends where user_id = ?)";
Вот тут конечно тоже затупил(

2023-01-19 08:54 UTC, NikolaiDem requested changes

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "from films as f inner join mpa_ratings as mr on f.mpa_rating_id = mr.id";
Лучше left join, чтобы в выборку попали все фильмы даже с пустым рейтингом.

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film : films) {
Здесь цикл не нужен, а нужен запрос в бд, который вернёт все жанры по переданному списку фильмов (id). Вот получен список жанров, теперь по нему можно поитерироваться и добавить его в соответствующий фильм.
И также сделать для лайков.

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDaoImpl.java
> +        jdbcTemplate.batchUpdate(sql, filmGenres, 50, (PreparedStatement ps, Genre genre) -> {
Почему 50? Нужно указать размер коллекции.

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        Set<Integer> userFriends = getFriends(userId).stream()
Можно вообще удалить друзей отсюда. Для этого можно использовать соответствующий эндпоинт.

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    private User mapRowUser(ResultSet rs, int rowNum) throws SQLException {
Друзей юзера можно не получать здесь)

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +//                "inner join users as u on f.friend_id = u.id " +
Здесь найдутся все юзеры, у которых id или userId или otherId. Нужно добавить ещё один джойн к друзьям и дополнительную проверку, что друг одного юзера совпадет с другом второго юзера.

2023-01-19 08:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        List<User> friends = jdbcTemplate.query(sql, this::mapRowUser, userId);
На одну связь создаётся же одна запись в бд ?
То есть, пусть юзер 1 дружит с юзерами 2,3,4. Но они только добавляли юзера 1.
То есть строки в бд:
2,1, true
3,1, true
4,1, true
Тогда данный метод вернёт 0 друзей юзера 1?

2023-01-19 23:32 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        List<User> friends = jdbcTemplate.query(sql, this::mapRowUser, userId);
Вопрос я понял) Я не понял как быть) Да, я проверил, действительно возвращается пустой список. Хотел попробовать добавить такую проверку, что если список в таком случае пустой, то пусть отправляется "перевернутый" запрос. Но такое решение приводило к бесконечному циклу. 
Неужели самый простой и верный вариант добавлять еще одну запись и будет получаться, что если дружба подтверждена между 1 и 2 пользователями, то будет такая запись:
1, 2;
2, 1; 
и нужда в булевом значении пропадет?

2023-01-20 18:33 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        Set<Integer> userFriends = getFriends(userId).stream()
Ок, убираю тогда. Просто думал что удобно будет, если получая юзера/список юзеров где бы то ни было, было бы хорошо видеть друзей этих юзеров) Но пока мне это доставляет лишние проблемы)

2023-01-20 18:36 UTC, cpu-fan commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        List<User> friends = jdbcTemplate.query(sql, this::mapRowUser, userId);
Слушай, вроде уже и не приводит к бесконечному циклу перевернутый запрос. Видимо дело было в чем-то другом.

2023-01-20 23:18 UTC, NikolaiDem requested changes

2023-01-20 23:18 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlGenres = "select * from genres where id in (:genreIds)";
С помощью джойна можно все сделать одним запросом:
Map<Integer, Film> filmMap = films.stream().collect(Collectors.toMap(Film::getId, Function.identity()));
        SqlParameterSource filmIdsSqlParam = new MapSqlParameterSource("filmIds", filmMap.keySet());
        String sqlGenres = "select * from genres g inner join film_genres fg on g.id = fg.genre_id where fg.film_id in (:filmIds)";
        namedJdbcTemplate.query(sqlGenres, filmIdsSqlParam,
                (rs) -> {
                    Genre genre = Genre.builder()
                            .id(rs.getInt("id"))
                            .name(rs.getString("name"))
                            .build();
                    filmMap.get(rs.getInt("fg.film_id")).getGenres().add(genre);
                }
        );

Аналогично для лайков.
И для UserDbStorage.setFriends(...)

2023-01-21 10:30 UTC, merged